### ISSUE TITLE
Maybe you should get rid of the when-failed macro...

### ISSUE THREAD

**Issue by ghost** [adambard/failjure#10]
I think it would be much better, if `attempt-all` would accept a plain function as a failure-handler instead of a `when-failed` macro - remember the first rule of the macro-club ;-)

And it just takes a slight modification:

```
(defmacro attempt-all
  "Used like `let`, but short-circuits in case of
  a failed binding. If a `failure-handler` fn is provided, it is called to handle the failure.
  Unlike `let`, only accepts a single form to execute after the bindings.
    (attempt-all [x \"Ok\"
                  y (fail \"Fail\")]
      x
      (fn handle-failure [e]
        (message e))) ; => \"Fail\"
  "
  ([bindings return]
   `(domonad error-m ~bindings ~return))
  ([bindings return failure-handler]
   `(let [result# (attempt-all ~bindings ~return)]
      (if (failed? result#)
        (~failure-handler result#)
        result#))))
```

What do you think?

Regards, Jan

**Comment by adambard** [comment]
Short answer: Yeah that would be better but not enough to release a breaking change. I'll keep it in mind for version 2 though ;)

I actually left it undocumented, but attempt-all can also be called with a regular form in the failure branch:

```clojure
(attempt-all [test (fail "Failure")]
  "Ok"
  "Failed") ; -> "Failed"
```

The problem here being that the original failure is lost, which was the position I found myself in when I started writing the when-failed macro, hence the weird metadata business.

**Comment by ghost** [comment]
I feel ya, breaking changes suck.
